SELECT CUSTOMER.Name, MAX(STREAM.Charge) AS N
	FROM CUSTOMER
		JOIN STREAM
		ON( CUSTOMER.CustomerId = STREAM.CustomerID )
	WHERE CUSTOMER.Country = 'United States' AND Year(STREAM.StreamDate) = 2018
	GROUP BY CUSTOMER.Name
	ORDER BY N DESC, CUSTOMER.Name;
