SELECT CUSTOMER.Name
	FROM CUSTOMER
		JOIN STREAM
			ON( CUSTOMER.CustomerId = STREAM.CustomerId )
		JOIN MOVIE
			ON( STREAM.MovieId = MOVIE.MovieId )
	WHERE Hour(STREAM.StreamDate) >= 20 AND MOVIE.Duration >= 180
	GROUP BY CUSTOMER.Name
	ORDER BY CUSTOMER.Name;
